version: '3.8'

x-common-variables: &common-variables
  MYSQL_DATABASE: db
  MYSQL_USER: MYSQL_USER
  MYSQL_PASSWORD: MYSQL_PASSWORD

services:
  mysql_db:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    restart: always
    cap_add:
      - SYS_NICE
    volumes:
      - "./mysql/sqls/20230605.sql:/docker-entrypoint-initdb.d/setup.sql"
    ports:
      - "9906:3306"
    environment:
      <<: *common-variables
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_HOST: mysql_db

  api:
    build:
      context: ./Back-End
      dockerfile: Dockerfile
    depends_on:
      - mysql_db
    volumes:
      - /app/node_modules
      - ./Back-End:/app
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: mysql_db

  client:
    stdin_open: true
    build:
      context: ./Front-End
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./Front-End:/app

  
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3050:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf


  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - 8000:8080
    depends_on:
      - mysql_db
    environment:
      ADMINER_DEFAULT_SERVER: mysql_db
